# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaDiUcqPgB0QtrUvMvjJ_vW9p8QEZs4U

# Assignment: Exploring Relationships in Data

This notebook aims to complete an assignment that involves exploring relationships in data, focusing on toxicity in comments from Wikipedia Talk Pages. The assignment is structured into the following steps:

1. Download and Understand the Dataset
2. Identify Protected Class Categories
3. Create a Reduced Dataset and Calculate Correlation
4. Population Statistics
5. Statistics for a Selected Protected Class Category
6. Statistics for Each Subgroup in Selected Protected Class Category
7. Plotting
8. Conclusion

Let's begin.

---

## Step 1: Download and Understand the Dataset

In this step, we will:

1. Download the dataset into a DataFrame.
2. Understand its structure by examining its columns and data types.

### Load the Dataset

First, we will load the dataset into a DataFrame and take a look at its first few rows.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Make plots inline
# %matplotlib inline

# --- 1. Load dataset ---
file_path = "toxity_per_attribute.csv"  # Ensure this is uploaded in Colab working dir
df = pd.read_csv(file_path)

print("✅ Dataset loaded successfully")
print("Shape:", df.shape)
print("Columns:", list(df.columns))



"""### Examine Data Types

Next, we will examine the data types of each column.
"""

df = df.replace({"TRUE": True, "FALSE": False})
for col in df.columns:
    if df[col].dtype == object:
        # Try to coerce True/False to int if possible
        if set(df[col].dropna().unique()).issubset({True, False, "TRUE", "FALSE"}):
            df[col] = df[col].replace({"TRUE": True, "FALSE": False}).astype(bool)
    # Convert boolean columns to int for correlation
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)

"""## Step 2: Identify Protected Class Categories

In this step, we will identify and list down all the potential protected class categories present in the dataset. These categories represent different groups or classes that are considered for analysis.
"""

protected_class_categories = {
    "Sexual Orientation": ['lesbian', 'gay', 'bisexual', 'transgender', 'trans', 'queer', 'lgbt', 'lgbtq', 'homosexual', 'straight', 'heterosexual'],
    "Gender Identity": ['male', 'female', 'nonbinary'],
    "Race/Ethnicity": ['african', 'african american', 'black', 'white', 'european', 'hispanic', 'latino', 'latina', 'latinx', 'mexican', 'canadian', 'american', 'asian', 'indian', 'middle eastern', 'chinese', 'japanese'],
    "Religion": ['christian', 'muslim', 'jewish', 'buddhist', 'catholic', 'protestant', 'sikh', 'taoist'],
    "Age/Disability": ['old', 'older', 'young', 'younger', 'teenage', 'millenial', 'middle aged', 'elderly', 'blind', 'deaf', 'paralyzed']
}
for k, v in protected_class_categories.items():
    protected_class_categories[k] = [c for c in v if c in df.columns]

print("\n✅ Protected class categories prepared:")
for k, v in protected_class_categories.items():
    print(f"  {k}: {v}")

"""## Step 3: Data Reduction & Correlation

In this step, we'll convert each subgroup column to numeric values. Then, we'll compute the correlation coefficients between each subgroup and the TOXICITY column and visualize it using a bar chart.
"""

corr = df.corr(numeric_only=True)["TOXICITY"].drop("TOXICITY", errors="ignore")
corr = corr[corr.index.isin([c for sublist in protected_class_categories.values() for c in sublist])]

if not corr.empty:
    plt.figure(figsize=(14, 6))
    corr.sort_values(ascending=False).plot(kind="bar", color="teal", edgecolor="black")
    plt.title("Correlation of TOXICITY with Each Protected Subgroup")
    plt.ylabel("Correlation Coefficient")
    plt.xlabel("Subgroups")
    plt.grid(axis="y", linestyle="--", alpha=0.7)
    plt.show()
else:
    print("⚠️ No numeric subgroup columns found for correlation.")

"""## Step 4: Population Statistics

In this step, we'll calculate the mean and standard deviation of the TOXICITY column for the entire dataset.
"""

results = []
population_mean = df["TOXICITY"].mean()
population_std = df["TOXICITY"].std()

for category, cols in protected_class_categories.items():
    category_rows = df[df[cols].sum(axis=1) > 0]
    category_mean = category_rows["TOXICITY"].mean()
    category_std = category_rows["TOXICITY"].std()

    results.append({"Category": category, "Subgroup": "Overall", "Mean": category_mean, "Std": category_std})

    for col in cols:
        subgroup_rows = df[df[col] == 1]
        if len(subgroup_rows) > 0:
            results.append({
                "Category": category,
                "Subgroup": col,
                "Mean": subgroup_rows["TOXICITY"].mean(),
                "Std": subgroup_rows["TOXICITY"].std()
            })

summary_df = pd.DataFrame(results)

"""## Step 5: Statistics for a Selected Protected Class Category

For the demonstration, we'll consider a category, for example, 'Religion'. We'll calculate the mean and standard deviation of the TOXICITY values associated with it. (Remember to replace 'Religion' with the actual category from your dataset).
"""

plt.figure(figsize=(10, 8))
plt.barh(summary_df["Subgroup"], summary_df["Mean"], xerr=summary_df["Std"], color="skyblue", edgecolor="black")
plt.title("Mean and Std Deviation of TOXICITY by Subgroup")
plt.xlabel("Mean TOXICITY")
plt.grid(axis="x", linestyle="--", alpha=0.7)
plt.show()

"""## Step 6: Statistics for Each Subgroup

In this step, we'll calculate the mean and standard deviation of TOXICITY values for each subgroup that is a member of the selected protected class category. For the demonstration, let's consider subgroups within the 'Religion' category.
"""

summary_df_valid = summary_df.dropna(subset=["Mean"])
if not summary_df_valid.empty:
    highest = summary_df_valid.loc[summary_df_valid["Mean"].idxmax()]
    lowest = summary_df_valid.loc[summary_df_valid["Mean"].idxmin()]

    print(f"🔥 Highest toxicity subgroup: {highest['Subgroup']} ({highest['Mean']:.3f}) in {highest['Category']}")
    print(f"🧊 Lowest toxicity subgroup: {lowest['Subgroup']} ({lowest['Mean']:.3f}) in {lowest['Category']}")
else:
    print("⚠️ No valid mean values found (check TOXICITY column).")

"""##Step 8: Conclusion
This concludes the assignment. We have gone through various steps to explore relationships in data, focusing on toxicity in comments from Wikipedia Talk Pages.
"""

summary_df.to_csv("toxicity_summary.csv", index=False)
print("\n✅ Results exported to 'toxicity_summary.csv'")
summary_df.head(10)
